services:
  - type: web
    name: sentient-ai-backend
    env: python
    buildCommand: "pip install poetry && poetry config virtualenvs.create false && poetry install --no-dev"
    startCommand: "poetry run uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: POETRY_VERSION
        value: 1.7.1
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        value: sqlite:///./sentient_ai.db
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        fromService:
          type: web
          name: sentient-ai-backend
          property: port
      - key: LOG_LEVEL
        value: INFO
      - key: FAISS_INDEX_PATH
        value: ./data/faiss_index
      - key: MAX_TOKENS_LIMIT
        value: 4000
      - key: RATE_LIMIT_REQUESTS
        value: 100
      - key: RATE_LIMIT_WINDOW
        value: 3600
    disk:
      name: sentient-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1 